# Generated by Codex on 2026-05-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseBackup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(blank=True, max_length=500, verbose_name="fichier")),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "En cours"), ("success", "Reussie"), ("failed", "Echouee")],
                        default="running",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField(default=0, verbose_name="taille octets")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("error_message", models.TextField(blank=True, verbose_name="erreur")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="cree le")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="termine le")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="database_backups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cree par",
                    ),
                ),
            ],
            options={
                "verbose_name": "sauvegarde base de donnees",
                "verbose_name_plural": "sauvegardes base de donnees",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=80, unique=True, verbose_name="cle")),
                ("label", models.CharField(max_length=150, verbose_name="libelle")),
                ("value", models.JSONField(blank=True, default=dict, verbose_name="valeur")),
                ("is_sensitive", models.BooleanField(default=False, verbose_name="sensible")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifie le")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_system_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifie par",
                    ),
                ),
            ],
            options={
                "verbose_name": "parametre systeme",
                "verbose_name_plural": "parametres systeme",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SystemActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Connexion"),
                            ("logout", "Deconnexion"),
                            ("login_failed", "Tentative echouee"),
                            ("sensitive_access", "Acces donnees sensibles"),
                            ("consultation_finished", "Consultation terminee"),
                            ("payment_created", "Paiement realise"),
                            ("backup_created", "Sauvegarde creee"),
                            ("admin_action", "Action admin"),
                        ],
                        max_length=40,
                        verbose_name="action",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="description")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="adresse IP")),
                ("user_agent", models.CharField(blank=True, max_length=255, verbose_name="navigateur")),
                ("path", models.CharField(blank=True, max_length=255, verbose_name="chemin")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="cree le")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "activite systeme",
                "verbose_name_plural": "activites systeme",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="clinic_comm_created_91da77_idx"),
                    models.Index(fields=["action", "-created_at"], name="clinic_comm_action_4d9bf4_idx"),
                ],
            },
        ),
    ]
