# Generated by Django 5.2.14 on 2026-05-14 22:16

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaissierAccount',
            fields=[
            ],
            options={
                'verbose_name': 'caissier',
                'verbose_name_plural': 'caissiers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InfirmierAccount',
            fields=[
            ],
            options={
                'verbose_name': 'infirmier',
                'verbose_name_plural': 'infirmiers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
