# Generated by Django 5.2.14 on 2026-05-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_caissieraccount_infirmieraccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infirmieraccount',
            options={'verbose_name': 'secretaire', 'verbose_name_plural': 'secretaires'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin'), ('infirmier', 'Secretaire'), ('caissier', 'Caissier'), ('admin', 'Administrateur')], default='patient', max_length=20),
        ),
    ]
