# Generated by Django 5.2.14 on 2026-05-14 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('doctor_ref', models.CharField(blank=True, max_length=200, verbose_name='réf. praticien')),
                ('service_ref', models.CharField(blank=True, max_length=200, verbose_name='réf. service')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_requests', to=settings.AUTH_USER_MODEL, verbose_name='compte associé')),
            ],
            options={
                'verbose_name': 'demande de rendez-vous',
                'verbose_name_plural': 'demandes de rendez-vous',
                'ordering': ['-created_at'],
            },
        ),
    ]
